### ISSUE TITLE
problem with mounting

### ISSUE THREAD

**Issue by Alneiry** [mk-fg/onedrive-fuse-fs#4]
when i mount through adding to /etc/fstab row

/var/lib/onedrive.yaml /home/eris/Data/OneDriveLinux fuse.onedrivefs  defaults 0 0

and then use command sudo mount -a  get next stacktrace

eris@nabster-linux:~/onedrive-fuse-fs$ sudo mount -a
Traceback (most recent call last):
  File "/usr/local/sbin/onedrivefs", line 75, in <module>
    class OneDriveFS(fuse.LoggingMixIn, fuse.Operations):
AttributeError: 'module' object has no attribute 'LoggingMixIn'

but i could mount my onedrive through command sudo onedrivefs /home/eris/Data/OneDriveLinux
and onedrive was in necessary folder but was available only for root user

**Comment by mk-fg** [comment]
I think the problem when mounting via command or fstab arises due to python importing something different than fuse.py as "fuse" (maybe some other bindings installed in the system using same name).

Can you try doing the following (as any user or root - shouldn't matter):
```
% cd /
% python2 -c 'import fuse; print fuse'
```

Should tell you where "fuse" module comes from on your system, if any.
`cd /` is to make sure python won't import the thing from current dir.

If it'll indeed show that there's another (presumably different) thing called "fuse" in your system, guess to avoid breaking anything that depends on it, you can do:
```
% python2 -c 'import sys; print sys.path'
```

And then:

* Rename "fuse.py" file from this repo to e.g. "fusepy.py" and put it into any system-wide path from the list printed by above command (avoid e.g. "/home/user/.local/...", as fstab will run script as root, and these will not be used there).

* In "onedrivefs" script, change `import fuse` line to `import fusepy as fuse`.

That should avoid such module naming conflict, if it's indeed the problem.

**Comment by mk-fg** [comment]
Btw, fuse.py in this repo comes from https://github.com/terencehonles/fusepy, so if you've installed it system-wide as suggested in the README via pip, before running command above, maybe run `pip uninstall fusepy` so it won't be left behind needlessly and/or won't break anything that depends on something different called "fuse" that you seem to have.

**Comment by mk-fg** [comment]
Uh... and by "running commands above" I meant only the latter thing with renaming fuse.py to fusepy.py and such.

**Comment by Alneiry** [comment]
after changing fusepy as you said i get next 
eris@nabster-linux:/$ sudo mount -a
Traceback (most recent call last):
  File "/usr/local/sbin/onedrivefs", line 319, in <module>
    if __name__ == '__main__': main()
  File "/usr/local/sbin/onedrivefs", line 309, in main
    api = api_v5.PersistentOneDriveAPI.from_conf(optz.config)
  File "/usr/local/lib/python2.7/dist-packages/onedrive/conf.py", line 46, in from_conf
    with open(path, 'rb') as src:
IOError: [Errno 2] No such file or directory: '/var/lib/onedrive.yaml'

**Comment by mk-fg** [comment]
Then I guess it works as expected now, you just don't have a config file there.
When you run the thing from cli with just a path, it uses ~/.lcrc (default for python-onedrive), but in fstab its path should be specified explicitly.

**Comment by Alneiry** [comment]
Thank you. folder finally mounted
But still has a problem that access to files has only root

string in fstab 
/home/eris/.lcrc /home/eris/Data/OneDriveLinux fuse.onedrivefs defaults 0 0

**Comment by mk-fg** [comment]
It's default fuse thing, I think you need to add "allow_other" option for it to allow access from other users.

**Comment by mk-fg** [comment]
Also, if you're mounting it into users' home, maybe adding user= would be appropriate, e.g.:

    /home/eris/.lcrc /home/eris/Data/OneDriveLinux fuse.onedrivefs user=eris,allow_other

That might need `user_allow_other` line in /etc/fuse.conf though.

**Comment by Alneiry** [comment]
Thank you for help. All works greate!
