### ISSUE TITLE
need help for new implementation of one-drive-fs 

### ISSUE THREAD

**Issue by Gorparth** [mk-fg/onedrive-fuse-fs#6]
I'm currently developing onedrivefs with python onedrivesdk, I've implemented till readdir but now I'm stuck at read,write,etc fucntions. can anyone please guide. I've stored path(folder or filename with folder) and id of it in one dictionary.

old code example:
def read(self, path, size, offset, fh):
		path_id = self._resolve(path)
		return self.api.get(path_id, byte_range='{}-{}'.format(offset, offset+size))

new example:
 def read(self, path, length, offset):
        logger.info("[read] (path=%s, length=%s, offset=%s)" % (path, length, offset))
        return authed_usr.client.item(id=authed_usr.folder[path]).download()

but this is not working, i'm attaching files please help me to implement. 

[onedrivefs.txt](https://github.com/mk-fg/onedrive-fuse-fs/files/6252963/onedrivefs.txt)
[onedrive_auth.txt](https://github.com/mk-fg/onedrive-fuse-fs/files/6252970/onedrive_auth.txt)

**Comment by Gorparth** [comment]
And this is my college project and deadline is coming so please help ASAP

**Comment by mk-fg** [comment]
Hi,

Can't really tell why it doesn't work, as I don't know what .download() returns, maybe some kind of object with metadata instead of bytes? 
Haven't used onedrive sdk myself, so don't really know off the top of my head how that works, but I'm sure it's well-documented and easy to just test quickly.

Also, shouldn't "read" signature be something like `read(self, path, length, offset, file_handle)` with fuse.py ctypes wrapper?
Seem to be in the ancient script that's in this repo at least.

And then also you don't seem to respect what exactly that syscall tried to read - i.e. returning .download() of what looks to be a complete file regardless of offset/length parameters, so I'd also suspect that FUSE might simply reject whatever you return to it because it doesn't match requested byte-length, as it doesn't know how to handle such larger chunk of data when it only can write specific subset of it to a pointer from requester read() syscall on the other end.

In any case, if there are no python errors and code runs (producing logging), then I'd suspect invalid return to fuse.py or FUSE API that it wraps around - you can probably add some extra logging there to check, see if there are more debug options for libfuse (likely are), or also run the app with e.g. strace to check what exactly happens on a syscall level there (like, what data ends up being passed to a kernel).
You can also load fuse module itself with debug paramameters and look into what happens there in other ways, but I'd bet that data doesn't get there, and gets rejected somewhere on the fuse.py or syscall level instead, which you can easily inspect like suggested above.

Not sure why you need to ask this question really, as you can go and dig deeper until you find the cause here - nothing should be opaque or hard-to-debug at these API layers, and seem to be obvious, as fuse.py is just python - add try-except/logging to whatever calls your read() backend there (or use pdb if you're more familiar with that), and that'll probably already tell you what the issue is.

Hope it helps, cheers!
